# Generated by Django 5.0.7 on 2024-07-27 11:39

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cartorder_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=15, max_length=20, prefix='ven', unique=True),
        ),
    ]
